name: CI/CD for Spring Boot

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Check current directory before
        run: ls -al target/

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install

      - name: Check current directory
        run: ls -al target/

      # - name: Upload build artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: springboot-jar
      #     path: target/*.jar

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Download built artifact
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: springboot-jar
  #         path: ./target

  #     - name: Deploy to server via SSH
  #       uses: appleboy/ssh-action@v1.0.0
  #       with:
  #         host: ${{ secrets.SSH_HOST }}
  #         username: ${{ secrets.SSH_USER }}
  #         key: ${{ secrets.SSH_PRIVATE_KEY }}
  #         script: |
  #           echo "Deploying Spring Boot App..."
  #           pkill -f 'java -jar' || true
  #           mkdir -p /var/www/demo_project
  #           rm -f /var/www/demo_project/*.jar
  #           # Copy JAR file from GitHub runner to server
  #           cat > /tmp/temp_jar_name
  #           exit
  #     - name: Copy JAR to Server
  #       uses: appleboy/scp-action@v0.1.7
  #       with:
  #         host: ${{ secrets.SSH_HOST }}
  #         username: ${{ secrets.SSH_USER }}
  #         key: ${{ secrets.SSH_PRIVATE_KEY }}
  #         source: "./target/*.jar"
  #         target: "/var/www/demo_project/"

  #     - name: Restart Application
  #       uses: appleboy/ssh-action@v1.0.0
  #       with:
  #         host: ${{ secrets.SSH_HOST }}
  #         username: ${{ secrets.SSH_USER }}
  #         key: ${{ secrets.SSH_PRIVATE_KEY }}
  #         script: |
  #           cd /var/www/demo_project
  #           nohup java -jar $(ls *.jar) > app.log 2>&1 &
  #           echo "Spring Boot app restarted successfully!"
